### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by surbhi24** [realm/realm-java#2168]
java.lang.StackOverflowError
at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:169)
at java.lang.StringBuilder.append(StringBuilder.java:311)
at java.lang.StringBuilder.append(StringBuilder.java:44)
at java.util.Formatter.outputCharSequence(Formatter.java:1094)
at java.util.Formatter.doFormat(Formatter.java:1066)
at java.util.Formatter.format(Formatter.java:1042)
at java.util.Formatter.format(Formatter.java:1011)
at java.lang.String.format(String.java:1999)
at java.lang.String.format(String.java:1973)
at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:188)
at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:173)
at io.realm.RealmConfiguration.<init>(RealmConfiguration.java:88)
at io.realm.RealmConfiguration.<init>(RealmConfiguration.java:54)
at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.java:415)

It happens while closing and deleting realm.

RealmConfiguration config = new RealmConfiguration.Builder(MyActivity)
                .schemaVersion(3)
                .migration(new RealmMigration())
                .build();
        try {
            realm.close();
            Realm.deleteRealm(config);
            Log.d(TAG, "REALM MIGRATION COMPLETED");
        } catch (Exception e) {
            Log.d(TAG, "REALM MIGRATION ERROR: " + e.toString());
            closeAndDeleteRealm();
        }
    }

**Comment by beeender** [comment]
Can you please share the full source of `closeAndDeleteRealm` ?
It looks like you have a recursive call without termination condition.

**Comment by surbhi24** [comment]
private void closeAndDeleteRealm() {

       RealmConfiguration config = new RealmConfiguration.Builder(MyActivity)
.schemaVersion(3)
.migration(new RealmMigration())
.build();
try {
realm.close();
Realm.deleteRealm(config);
Log.d(TAG, "REALM MIGRATION COMPLETED");
startMainActivity();
} catch (Exception e) {
Log.d(TAG, "REALM MIGRATION ERROR: " + e.toString());
closeAndDeleteRealm();
}
}
    }

**Comment by beeender** [comment]
Well, as I said, it is a recursive call without termination condition. In the catch block, you are trying to call `closeAndDeleteRealm()` again which leads to another exception in the next recursion call.

You need to figure out what is the exception in the catch block, and fix it. Ignoring exception and trying again won't solve any problem.

What is the exception you caught?

**Comment by surbhi24** [comment]
IllegalStateException

**Comment by beeender** [comment]
But `IllegalStateException` with what message? It is really difficult for us to solve any problem with such limited information ...

**Comment by surbhi24** [comment]
I am catching iIllegalStateException(), cannot see the detail as not logged in logs.

**Comment by beeender** [comment]
Exception like `IllegalStateException` should be fixed not just catch it. http://stackoverflow.com/questions/2416316/why-is-the-catchexception-almost-always-a-bad-idea to see why you should not do that.

You need figure out where it is throwing the `IllegalStateException`, and what exactly the `IllegalStateException` is, then solve it.

**Comment by surbhi24** [comment]
Basically it says this...java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm. Remember to close() all the instances of the Realm before deleting its file

**Comment by beeender** [comment]
As it said, you have some Realm instance is not closed. You **have to** make sure every Realm instance gets closed (call `Realm.close`) before calling `Realm.deleteRealm'.

**Comment by surbhi24** [comment]
I am calling Realm.close() before deleteRealm(), still this stackoverflow error persists.

**Comment by beeender** [comment]
You **have to** make sure **every** Realm instance gets closed (call Realm.close) before calling Realm.deleteRealm.

Means, if you called `getInstance` once, you have to call `close` once because of internally Realm is using reference counter to create only one instance for every thread. A missing `close` will potentially cause memory leak.

**Comment by surbhi24** [comment]
Yes, realm.close() is called everywhere we have called getDefaultInstance() of Realm, which we have defined in our main application.

**Comment by cmelchior** [comment]
Hi @surbhi24 
You are only getting that exception if some instance hasn't been closed yet. Note that you also have to close all instances on other threads as well and there might be race conditions involved in that unless you somehow synchronize that across the threads.

**Comment by kneth** [comment]
I am closing the issue since I believe we have answered it. @surbhi24 Don't hesitate to reopen or create a new issue if you are experiencing the issue in the future.
