### ISSUE TITLE
Permission denied in io_realm_internal_SharedGroup.cpp using internal storage only

### ISSUE THREAD

**Issue by franmontiel** [realm/realm-java#3895]
I've received the crash in Crashlytics. It only happened in one device for now and I am not able to reproduce on my devices.

At first I thought it was related with #3413 but I'm only using internal storage. It is happening in a Huawei G8 phone so might be related with #3892...

The call that is firing the exception is `Realm.getDefaultInstance()` and this is my Realm configuration:
```java
 Realm.setDefaultConfiguration(
                new RealmConfiguration.Builder(this)
                        .name("primor.realm")
                        .schemaVersion(1)
                        .deleteRealmIfMigrationNeeded()
                        .build()
        );
```
This is the stack trace:
```
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in io_realm_internal_SharedGroup.cpp line 113
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)
       at io.realm.internal.SharedGroup.(SharedGroup.java)
       at io.realm.internal.SharedGroupManager.(SharedGroupManager.java)
       at io.realm.BaseRealm.(BaseRealm.java)
       at io.realm.Realm.(Realm.java)
       at io.realm.Realm.createAndValidate(Realm.java:239)
       at io.realm.Realm.createInstance(Realm.java:219)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
       at io.realm.Realm.getDefaultInstance(Realm.java:165)
       at com.spiralapps.primor.data.datasources.database.DbCacheDataSource.isCached(DbCacheDataSource.java:68)
       at com.franmontiel.commons.data.BaseRepository.load(BaseRepository.java:84)
       at com.spiralapps.primor.data.ProductRepositoryImp.getProducts(ProductRepositoryImp.java:37)
       at com.spiralapps.primor.domain.shop.products.GetProductsImp.executeRepositoryCall(GetProductsImp.java:34)
       at com.spiralapps.primor.domain.shop.products.GetProductsImp.executeRepositoryCall(GetProductsImp.java:14)
       at com.franmontiel.commons.domain.SimpleInteractor.run(SimpleInteractor.java:25)
       at com.franmontiel.commons.domain.executor.ThreadExecutor$1.run(ThreadExecutor.java:56)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:833)
```
#### Version of Realm and tooling
Realm version(s): 1.1.1 (I haven't updated because I did not see any mention to this issue in the changelog)
Realm sync feature enabled: no
Android Studio version: 2.2.2
Android version and device: HUAWEI RIO-L01 (Huawei G8) with Android 6.0.1

**Comment by kneth** [comment]
@franmontiel Yes, it sounds very much like #3892. Thanks for providing additional details (configuration and longer complete stack trace).

**Comment by beeender** [comment]
@franmontiel this should have been fixed on our master already. Is it possible you can help to verify with our snapshot release on Huawei G8? I tested on Huawei hornor 7 and it works. 
Thanks!

**Comment by tamtom** [comment]
hey guys what happen with this crash

**Comment by kneth** [comment]
@franmontiel Did you have a chance to test with a snapshot release?

**Comment by franmontiel** [comment]
@kneth The problem is that I am not able to reproduce the issue by myself because I don't have any Huawei device to test it.

What I can confirm is that the problem seems to only affect Huawei devices, I received a new crash report from a Huawei P8lite,

**Comment by kneth** [comment]
@franmontiel We have released 2.2.2 a few hours ago. Please try to upgrade and report back.

**Comment by kneth** [comment]
@franmontiel We have released 2.3.0 too.

**Comment by radzish** [comment]
It still happened in 2.3.0 version on HUAWEI MT7-L09

**Comment by hmedat2008** [comment]
Any updates about this crash

**Comment by beeender** [comment]
@hmedat2008
can you still reproduce this issue with the latest release? 
on what devices?
what android version?
what is your Realm configuration?
what is the full backtrace stack & crash info?

thanks.

**Comment by Zhuinden** [comment]
Something similar can still happen as per https://github.com/realm/realm-java/issues/5715
