### ISSUE TITLE
denied { create } for name="access_control.new_commit.cv" 

### ISSUE THREAD

**Issue by ldf1210750006** [realm/realm-java#4630]
run my project on android5 or android6 is ok,  but on android7.1.1,there is a bug:
> **Bugs**:  E/REALM_JNI: jni: ThrowingException 5, Permission denied in /Users/blakemeike/Working/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 94, .
type=1400 audit(0.0:315): avc: denied { create } for name="access_control.new_commit.cv" scontext=u:r:system_app:s0 tcontext=u:object_r:system_app_data_file:s0 tclass=fifo_file permissive=0
 at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                                     at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:209)
                                                                     at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:186)
                                                                     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:124)
                                                                     at io.realm.DynamicRealm.getInstance(DynamicRealm.java:67)
                                                                     at io.realm.BaseRealm$4.onResult(BaseRealm.java:634)
                                                                     at io.realm.RealmCache.invokeWithGlobalRefCount(RealmCache.java:295)
                                                                     at io.realm.BaseRealm.migrateRealm(BaseRealm.java:617)
                                                                     at io.realm.Realm.migrateRealm(Realm.java:1577)
#### Version of Realm and tooling
Realm version(s): 2.3.0

Realm sync feature enabled: yes

Android Studio version: 2.2.3

Which Android version and device: android7.1.1，

**Comment by kneth** [comment]
@ldf1210750006 Can you provide the code? It seems to happen during migration?

**Comment by ldf1210750006** [comment]
I think it does not happen in Migrate, because it can run on Android5.0, 6.0, but not in Android7.1.1. I think it is a permissions issue, there is no permission to create "access_control.new_commit.cv". This is my code:
```java
public static void init(Context context,String realmName, int databaseVersion, RealmMigration migration) {
        byte[] key = new byte[64];
        new SecureRandom().nextBytes(key);
        if (realmConfiguration == null) {
            realmConfiguration = new RealmConfiguration
                    .Builder()
                    .directory(getCaminhoDB(context))
                    .name(initName(realmName))
                    .schemaVersion(databaseVersion)
                    .build();
        }
        File realmFile = new File(realmConfiguration.getPath());
        if (!realmFile.exists()) {
            try {
                realmFile.createNewFile();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        try {
            Realm.migrateRealm(realmConfiguration, migration);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        Realm.setDefaultConfiguration(realmConfiguration);
    }

    private static File getCaminhoDB(@NonNull Context context) {
        if (isExternalStorageWritable()) {
            return context.getExternalFilesDir("database");
        } else {
            return context.getFilesDir();
        }
    }
```

**Comment by beeender** [comment]
@ldf1210750006 Can you try with a the latest realm-java release? we fixed a similar error in 3.1.3

**Comment by ldf1210750006** [comment]
I am using version 3.1.3, but this problem still exists

**Comment by kneth** [comment]
@ldf1210750006 Can you share a small project which reproduces the error?

**Comment by Zhuinden** [comment]
What is `  .directory(getCaminhoDB(context))`?

**Comment by ldf1210750006** [comment]
.directory(getCaminhoDB(context))，This method is used to define the storage path, even if I delete this, the error still exists.

when I initialize the name and version number in my application，this error has occurred，as follows：
Realm.init(this);
RealmInit.init(this,"phone.realm", 3, new PhoneMigrate());

public class PhoneMigrate implements RealmMigration {....}

**Comment by ldf1210750006** [comment]
@cmelchior Can you give me some advise? An error occurred while I was initializing Realm, and the following version of Android7.0 is available, but it cannot run on Android7.1.1, so I think it's a privilege problem.

**Comment by cmelchior** [comment]
I would try upgrading to 3.2.0 which is the latest version. There has been a few problems with specific devices and Realm files on external storage that has been fixed between 2.3.0 and 3.2.0

**Comment by Zhuinden** [comment]
3.1.4's 

> Initializing Realm is now more resilient if Context.getFilesDir() isn't working correctly (#4493).

might help with this.

**Comment by bmeike** [comment]
@ldf1210750006 Please note that we have yet to get any code from you that would allow us to reproduce this problem.  If you have something to share, it would be a huge help in addressing the issue.

**Comment by ldf1210750006** [comment]
@bmeike  This is my step of use：
1、Initialize in my application：
```java
Realm.init(this);
RealmInit.init(this,"phone.realm", 3, new PhoneMigrate());
```
2、this is my RealmInit.java
```java
public static void init(Context context,String realmName, int databaseVersion, RealmMigration migration) {
        byte[] key = new byte[64];
        new SecureRandom().nextBytes(key);
        if (realmConfiguration == null) {
            realmConfiguration = new RealmConfiguration
                    .Builder()
                    .directory(getCaminhoDB(context))
                    .name(initName(realmName))
                    .schemaVersion(databaseVersion)
                    .build();
        }
        File realmFile = new File(realmConfiguration.getPath());
        if (!realmFile.exists()) {
            try {
                realmFile.createNewFile();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        try {
            Realm.migrateRealm(realmConfiguration, migration);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        Realm.setDefaultConfiguration(realmConfiguration);
    }

    private static File getCaminhoDB(@NonNull Context context) {
        if (isExternalStorageWritable()) {
            return context.getExternalFilesDir("database");
        } else {
            return context.getFilesDir();
        }
    }
```
The above error occurred，Whether I call getCaminhoDB() or delete migrateRealm, this error still exists.I wonder if this code works?

**Comment by bmeike** [comment]
Thanks @ldf1210750006 .  We are looking into it.

**Comment by ldf1210750006** [comment]
I failed to quote 3.2.2-SNAPSHOT

**Comment by zaki50** [comment]
@ldf1210750006 It might not be related to this issue, you should not create empty realm file.
It's not a valid Realm database file.

**Comment by zaki50** [comment]
@ldf1210750006 I couldn't reproduce this on Android 7.0 device and 7.1.1 x86 emulator.
I'll try it on actual 7.1.1 device later.

Could you provide a complete project that reproduce this issue?

**Comment by zaki50** [comment]
I tried on Nexus 9 (Android 7.1.1) and could not reproduce it.

Which device are you using?

**Comment by ldf1210750006** [comment]
I'm using one plus 3

**Comment by beeender** [comment]
@ldf1210750006 What ROM are you using? I think H2OS doesn't have official support for `7.1.1`?

**Comment by ldf1210750006** [comment]
I'm using OP3_H2_OPEN_14
@beeender Did you reproduce the above error?

**Comment by beeender** [comment]
nope, we haven't got a phone yet.
Just to confirm, is your phone Oneplus 3 or Oneplus 3T ?

**Comment by ldf1210750006** [comment]
my phone is Oneplus 3.

**Comment by ldf1210750006** [comment]
I ran my project with the native 7.1.1 system just now, there is another error:
```java
java.lang.UnsatisfiedLinkError: No implementation found for void io.realm.internal.SharedRealm.nativeSetAutoRefresh(long, boolean) (tried Java_io_realm_internal_SharedRealm_nativeSetAutoRefresh and Java_io_realm_internal_SharedRealm_nativeSetAutoRefresh__JZ)
                                                                     at io.realm.internal.SharedRealm.nativeSetAutoRefresh(Native Method)
                                                                     at io.realm.internal.SharedRealm.<init>(SharedRealm.java:201)
                                                                     at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:240)
                                                                     at io.realm.BaseRealm.<init>(BaseRealm.java:91)
                                                                     at io.realm.DynamicRealm.<init>(DynamicRealm.java:55)
                                                                     at io.realm.DynamicRealm.createInstance(DynamicRealm.java:244)
                                                                     at io.realm.BaseRealm$4.onResult(BaseRealm.java:653)
                                                                     at io.realm.RealmCache.invokeWithGlobalRefCount(RealmCache.java:481)
                                                                     at io.realm.BaseRealm.migrateRealm(BaseRealm.java:634)
                                                                     at io.realm.Realm.migrateRealm(Realm.java:1709)
```

**Comment by beeender** [comment]
@ldf1210750006 that sound like a build problem, try `./gradlew build --refresh-dependencies`

**Comment by ldf1210750006** [comment]
yes,now I can run my project with native 7.1.1 systems。

**Comment by ldf1210750006** [comment]
now,If I run the setenforce 0 command with adb, to set SELinux to permissive mode,So I can run my project properly。

**Comment by nhachicha** [comment]
- `new SecureRandom().nextBytes(key);` are you generating a new key every time you call `init` ?

**Comment by ldf1210750006** [comment]
yes,every time,i will get a new key.

**Comment by Zhuinden** [comment]
How will you open a previously created Realm? Or do you delete it?

You might want to make it `inMemory()` then.

**Comment by ldf1210750006** [comment]
i want to make it inMemory(),When I operate the Realm database, I first get the default configuration and close it when I run out.

**Comment by ldf1210750006** [comment]
I think this is the system permissions，because If I run the following command, this error will disappear and my project will work properly：
```java
C:\Users\Administrator>adb shell
shell@M2000:/ $ su
root@M2000:/ # setenforce 0
```

**Comment by beeender** [comment]
[app-debug.zip](https://github.com/realm/realm-java/files/1057638/app-debug.zip)

@ldf1210750006 Can you please try to install this testing apk and tell me what is the output on the screen?
please try with `setenforce 1`

**Comment by ldf1210750006** [comment]
I didn't find any special output,I don't know what is your expected

**Comment by beeender** [comment]
@ldf1210750006 I printed some debug information on the phone screen.
So if you run the apk attached in comment https://github.com/realm/realm-java/issues/4630#issuecomment-306749725 with `setenforce 1`, you will be able to see some think like:
```
mkfifo on internal results: xx, xx
on external: xx, xx
```

Would you please run that apk and take a screenshot for us? thanks.

**Comment by kneth** [comment]
@ldf1210750006 Did you have a chance to try the APK mentioned above?

**Comment by ldf1210750006** [comment]
setenforce 1:
```java
06-26 16:44:01.088 6441-6441/tt.test.fifotest V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@53836f2
06-26 16:44:01.088 6441-6441/tt.test.fifotest V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@ad95143
06-26 16:44:01.187 6441-6441/tt.test.fifotest A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 6441 (t.test.fifotest)
                                                      
                                                      [ 06-26 16:44:01.188   285:  285 W/         ]
                                                      debuggerd: handling request: pid=6441 uid=10022 gid=10022 tid=6441
```
setenforce 0:
```java
06-26 16:42:25.280 6441-6441/? I/art: Late-enabling -Xcheck:jni
06-26 16:42:25.502 6441-6441/tt.test.fifotest W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
06-26 16:42:25.580 6441-6441/tt.test.fifotest V/BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
06-26 16:42:25.580 6441-6441/tt.test.fifotest V/BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
06-26 16:42:25.581 6441-6441/tt.test.fifotest V/BoostFramework: mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
06-26 16:42:25.581 6441-6441/tt.test.fifotest V/BoostFramework: mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
06-26 16:42:25.742 6441-6441/tt.test.fifotest I/t.test.fifotest: type=1400 audit(0.0:143): avc: denied { create } for name="fifotest" scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:fuse:s0:c512,c768 tclass=fifo_file permissive=1
06-26 16:42:25.581 6441-6441/tt.test.fifotest V/BoostFramework: mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
06-26 16:42:25.597 6441-6441/tt.test.fifotest E/linker: library "/vendor/lib/libqti_performance.so" ("/system/vendor/lib/libqti_performance.so") needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="", permitted_paths="/data:/mnt/expand"]
06-26 16:42:25.599 6441-6441/tt.test.fifotest V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@f456563
06-26 16:42:25.599 6441-6441/tt.test.fifotest V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@3028560
06-26 16:42:26.234 6441-6468/tt.test.fifotest D/libEGL: loaded /vendor/lib/egl/libEGL_adreno.so
06-26 16:42:26.258 6441-6468/tt.test.fifotest D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_adreno.so
06-26 16:42:26.360 6441-6468/tt.test.fifotest D/libEGL: loaded /vendor/lib/egl/libGLESv2_adreno.so
06-26 16:42:26.404 6441-6468/tt.test.fifotest I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8909w_LAW.BR.2.0_RB1__release_AU (Ic9237b88bb)
                                                            OpenGL ES Shader Compiler Version: E031.31.00.02
                                                            Build Date: 01/27/17 Fri
                                                            Local Branch: mybranch24592193
                                                            Remote Branch: quic/LAW.BR.2.0_rb1.8
                                                            Local Patches: NONE
                                                            Reconstruct Branch: NOTHING
06-26 16:42:26.414 6441-6468/tt.test.fifotest I/OpenGLRenderer: Initialized EGL, version 1.4
06-26 16:42:26.415 6441-6468/tt.test.fifotest D/OpenGLRenderer: Swap behavior 1

```

**Comment by beeender** [comment]
@ldf1210750006 sorry, I didn't make it clear. I print the output to the **phone screen** . So are there any difference on the **phone screen** for `setenforce 1:` and `setenforce 0:` ?

**Comment by ldf1210750006** [comment]
setenforce 1:
FifoTest has stopped running
setenforce 0:
mkfifo on internal results: 0, 17
on external: 0, 17

**Comment by beeender** [comment]
Thanks! I will update the apk to get more info for the `setenforce 1` case. It is annoy that no native backtrace when native crash happened. I will let you know when the new apk is ready, still need more help to locate the issue.

**Comment by cmelchior** [comment]
@beeender Had a chance to look at this?

**Comment by beeender** [comment]
nope, I am working on #3972 now, they probably share the same root cause.

**Comment by beeender** [comment]
close this one. This probably is a ROM issue.
