### ISSUE TITLE
Deleting from RealmList throws exception

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#875]
Hi @cmelchior 
I am probably experiencing the same issue. I am using ver. 0.79.0.
```Stacktrace
FATAL EXCEPTION: main
java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows.
at io.realm.internal.LinkView.nativeRemove(Native Method)
at io.realm.internal.LinkView.remove(LinkView.java:67)
at io.realm.RealmList.remove(RealmList.java:189)
at com.sampleapp.MergedCardsListClick$1.onClick(MergedCardsListClick.java:64)
...
at dalvik.system.NativeStart.main(Native Method)
```
This issue happens when I try to delete the last element in `RealmList`. Here is my code:
```Java
for (int i = 0; i < parent.getChildren().size(); i++) {
	if (parent.getChildren().get(i).get_id() == object.get_id()) {
		mRealm.beginTransaction();
		parent.getChildren().remove(i); // Line that throws ArrayIndexOutOfBoundsException
		mRealm.commitTransaction();
		break;
	}
}
```
The strange thing is that when I try to delete any element but not last, it does not crash. But when I try to delete the last element (again, **any** element), it crashes.
So I changed the code a bit to make it work: (maybe somebody will find it helpful)
```Java
for (int i = 0; i < size; i++) {
	if (parent.getChildren().get(i).get_id() == sms.get_id()) {
		mRealm.beginTransaction();
		if (size != 1) {
			parent.getChildren().remove(i); // does not crash
		} else {
			parent.getChildren().clear(); // does not crash
		}
		mRealm.commitTransaction();
		break;
	}
}
```
My model:
```Java
package com.sampleapp;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.Index;
import io.realm.annotations.RealmClass;

@RealmClass
public class Parent extends RealmObject {
	private long _id;

	@Index
	private String originalText;
	private Parent parent;
	private RealmList<Parent> children;

	public long get_id() {
		return _id;
	}

	public void set_id(long _id) {
		this._id = _id;
	}

	public String getOriginalText() {
		return originalText;
	}

	public void setOriginalText(String originalText) {
		this.originalText = originalText;
	}

	public Parent getParent() {
		return parent;
	}

	public void setParent(Parent parent) {
		this.parent = parent;
	}

	public RealmList<Parent> getChildren() {
		return children;
	}

	public void setChildren(RealmList<Parent> children) {
		this.children = children;
	}
}
```
Summary: 
* It crashes every time. (I've seen it multiple times)
* It is reproducable.
* Experienced crashes on Android 4.1.2 (Samsung Galaxy S3), 4.4.4. (Sony Z3 Compact)
* Happens when a user taps on the button in order to delete the last child.

**Comment by cmelchior** [comment]
A fix has been merged to master.

**Comment by Sourabh-Tag** [comment]
Issues is still present in 0.80.3

**Comment by Sourabh-Tag** [comment]
the things i tried 
realm.allObjects(CompanyDTO.class).get(viewHolder.getAdapterPosition()).removeFromRealm();
and
realm.allObjects(CompanyDTO.class).remove(viewHolder.getAdapterPosition());
//(viewHolder.getAdapterPosition() gives me the position)

and finally it worked with this

RealmResults<CompanyDTO> result2 = realm.where(CompanyDTO.class).equalTo("id", ""+viewHolder.getAdapterPosition()).findAll();
                Log.e("TAG", ""+result2);
                result2.removeAll(result2);

and I am using 
compile 'io.realm:realm-android:0.81.0-SNAPSHOT'

Thanks

**Comment by kneth** [comment]
@Sourabh-Tag Currently, removing objects using a `RealmResultsIterator` isn't supported. The reason is that if another thread is changing the Realm, the `RealmResults` is changed, and we cannot be certain that the object which you wish to remove is still present in the Realm.

**Comment by vijaemanlapaz** [comment]
hi @kneth can you take a look at #1289

**Comment by cmelchior** [comment]
I tried the following, which test all combinations of removing objects from a result set. Neither of these fail with `0.82.1`

```
// Query results
   public void testRemoveLastItemFromQueryResult() {
        populateTestRealm(TEST_DATA_SIZE);
        RealmResults<AllTypes> result = testRealm.allObjects(AllTypes.class);
        testRealm.beginTransaction();
        try {
            result.removeLast();
            assertEquals(TEST_DATA_SIZE - 1, result.size());
            result.remove(TEST_DATA_SIZE - 2);
            assertEquals(TEST_DATA_SIZE - 2, result.size());
            result.get(TEST_DATA_SIZE - 3).removeFromRealm();
            assertEquals(TEST_DATA_SIZE - 3, result.size());
        } finally {
            testRealm.cancelTransaction();
        }
    }
```

Closing for now as we cannot reproduce this. If you still see this error please try to reproduce in a small sample project you can send us.

**Comment by xbroak** [comment]
I am also having this issue:

rowIndex > available rows: 3 > 3

Using:

    realm.beginTransaction();
            for (int i = 0; i < result.size(); i++) {
                if (result.get(i).getId().equals(id)) {
                    result.get(i).removeFromRealm();
                }
            }
            realm.commitTransaction();

**Comment by HsiangLeekwok** [comment]
I am having this issue too(realm 0.87.5):
by use:
```Java
someResults.get(someIndex);
```
and throws this exception:
```Java
java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows: 0 > 0
	at io.realm.internal.TableView.nativeGetSourceRowIndex(Native Method)
	at io.realm.internal.TableView.getSourceRowIndex(TableView.java:127)
	at io.realm.RealmResults.get(RealmResults.java:174)
```

**Comment by cmelchior** [comment]
@xbroak @HsiangLeekwok 
It is because RealmResults are "live" views, which means they are updated as soon as you do an action that effects them. In this case removing the object.

We are working on improving this so iterators have a bit more natural behavior (tracked by this bug #602), but in the meantime you can use the work-around described here: https://github.com/realm/realm-java/issues/640#issuecomment-103798064

**Comment by Zhuinden** [comment]
Results are no longer live since 0.89.0

They are updated on the next looper event, so to be notified of when they are auto-updated, a `RealmChangeListener` should be used

**Comment by Isabellle** [comment]
Thank you!
